// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iSOFlair {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelUsername")]
		private MonoTouch.UIKit.UILabel labelUsername {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelUsername")));
			}
			set {
				this.SetNativeField("labelUsername", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelPoints")]
		private MonoTouch.UIKit.UILabel labelPoints {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelPoints")));
			}
			set {
				this.SetNativeField("labelPoints", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageviewGravatar")]
		private MonoTouch.UIKit.UIImageView imageviewGravatar {
			get {
				return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageviewGravatar")));
			}
			set {
				this.SetNativeField("imageviewGravatar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelLastUpdated")]
		private MonoTouch.UIKit.UILabel labelLastUpdated {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelLastUpdated")));
			}
			set {
				this.SetNativeField("labelLastUpdated", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonUpdate")]
		private MonoTouch.UIKit.UIButton buttonUpdate {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonUpdate")));
			}
			set {
				this.SetNativeField("buttonUpdate", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelBronzeBadges")]
		private MonoTouch.UIKit.UILabel labelBronzeBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelBronzeBadges")));
			}
			set {
				this.SetNativeField("labelBronzeBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelGoldBadges")]
		private MonoTouch.UIKit.UILabel labelGoldBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelGoldBadges")));
			}
			set {
				this.SetNativeField("labelGoldBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelSilverBadges")]
		private MonoTouch.UIKit.UILabel labelSilverBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelSilverBadges")));
			}
			set {
				this.SetNativeField("labelSilverBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelConnectionError")]
		private MonoTouch.UIKit.UILabel labelConnectionError {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelConnectionError")));
			}
			set {
				this.SetNativeField("labelConnectionError", value);
			}
		}
	}
}
