// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iSOFlair {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SOViewController")]
	public partial class SOViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_labelPoints;
		
		private MonoTouch.UIKit.UILabel __mt_labelUsername;
		
		private MonoTouch.UIKit.UIButton __mt_buttonUpdate;
		
		private MonoTouch.UIKit.UIImageView __mt_imageAvatar;
		
		private MonoTouch.UIKit.UIImageView __mt_imageLogo;
		
		private MonoTouch.UIKit.UILabel __mt_labelBronzeBadges;
		
		private MonoTouch.UIKit.UILabel __mt_labelGoldBadges;
		
		private MonoTouch.UIKit.UILabel __mt_labelSilverBadges;
		
		private MonoTouch.UIKit.UILabel __mt_labelConnectionError;
		
		private MonoTouch.UIKit.UILabel __mt_labelLastUpdated;
		
		private MonoTouch.UIKit.UITextView __mt_textDebug;
		
		private MonoTouch.UIKit.UIButton __mt_buttonSafari;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelPoints")]
		private MonoTouch.UIKit.UILabel labelPoints {
			get {
				this.__mt_labelPoints = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelPoints")));
				return this.__mt_labelPoints;
			}
			set {
				this.__mt_labelPoints = value;
				this.SetNativeField("labelPoints", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelUsername")]
		private MonoTouch.UIKit.UILabel labelUsername {
			get {
				this.__mt_labelUsername = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelUsername")));
				return this.__mt_labelUsername;
			}
			set {
				this.__mt_labelUsername = value;
				this.SetNativeField("labelUsername", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonUpdate")]
		private MonoTouch.UIKit.UIButton buttonUpdate {
			get {
				this.__mt_buttonUpdate = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonUpdate")));
				return this.__mt_buttonUpdate;
			}
			set {
				this.__mt_buttonUpdate = value;
				this.SetNativeField("buttonUpdate", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageAvatar")]
		private MonoTouch.UIKit.UIImageView imageAvatar {
			get {
				this.__mt_imageAvatar = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageAvatar")));
				return this.__mt_imageAvatar;
			}
			set {
				this.__mt_imageAvatar = value;
				this.SetNativeField("imageAvatar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageLogo")]
		private MonoTouch.UIKit.UIImageView imageLogo {
			get {
				this.__mt_imageLogo = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageLogo")));
				return this.__mt_imageLogo;
			}
			set {
				this.__mt_imageLogo = value;
				this.SetNativeField("imageLogo", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelBronzeBadges")]
		private MonoTouch.UIKit.UILabel labelBronzeBadges {
			get {
				this.__mt_labelBronzeBadges = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelBronzeBadges")));
				return this.__mt_labelBronzeBadges;
			}
			set {
				this.__mt_labelBronzeBadges = value;
				this.SetNativeField("labelBronzeBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelGoldBadges")]
		private MonoTouch.UIKit.UILabel labelGoldBadges {
			get {
				this.__mt_labelGoldBadges = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelGoldBadges")));
				return this.__mt_labelGoldBadges;
			}
			set {
				this.__mt_labelGoldBadges = value;
				this.SetNativeField("labelGoldBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelSilverBadges")]
		private MonoTouch.UIKit.UILabel labelSilverBadges {
			get {
				this.__mt_labelSilverBadges = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelSilverBadges")));
				return this.__mt_labelSilverBadges;
			}
			set {
				this.__mt_labelSilverBadges = value;
				this.SetNativeField("labelSilverBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelConnectionError")]
		private MonoTouch.UIKit.UILabel labelConnectionError {
			get {
				this.__mt_labelConnectionError = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelConnectionError")));
				return this.__mt_labelConnectionError;
			}
			set {
				this.__mt_labelConnectionError = value;
				this.SetNativeField("labelConnectionError", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelLastUpdated")]
		private MonoTouch.UIKit.UILabel labelLastUpdated {
			get {
				this.__mt_labelLastUpdated = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelLastUpdated")));
				return this.__mt_labelLastUpdated;
			}
			set {
				this.__mt_labelLastUpdated = value;
				this.SetNativeField("labelLastUpdated", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textDebug")]
		private MonoTouch.UIKit.UITextView textDebug {
			get {
				this.__mt_textDebug = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("textDebug")));
				return this.__mt_textDebug;
			}
			set {
				this.__mt_textDebug = value;
				this.SetNativeField("textDebug", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonSafari")]
		private MonoTouch.UIKit.UIButton buttonSafari {
			get {
				this.__mt_buttonSafari = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonSafari")));
				return this.__mt_buttonSafari;
			}
			set {
				this.__mt_buttonSafari = value;
				this.SetNativeField("buttonSafari", value);
			}
		}
	}
}
