// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Swipe01 {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SOViewController")]
	public partial class SOViewController {
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelPoints")]
		private MonoTouch.UIKit.UILabel labelPoints {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelPoints")));
			}
			set {
				this.SetNativeField("labelPoints", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelUsername")]
		private MonoTouch.UIKit.UILabel labelUsername {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelUsername")));
			}
			set {
				this.SetNativeField("labelUsername", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonUpdate")]
		private MonoTouch.UIKit.UIButton buttonUpdate {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonUpdate")));
			}
			set {
				this.SetNativeField("buttonUpdate", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageAvatar")]
		private MonoTouch.UIKit.UIImageView imageAvatar {
			get {
				return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageAvatar")));
			}
			set {
				this.SetNativeField("imageAvatar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageLogo")]
		private MonoTouch.UIKit.UIImageView imageLogo {
			get {
				return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageLogo")));
			}
			set {
				this.SetNativeField("imageLogo", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelBronzeBadges")]
		private MonoTouch.UIKit.UILabel labelBronzeBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelBronzeBadges")));
			}
			set {
				this.SetNativeField("labelBronzeBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelGoldBadges")]
		private MonoTouch.UIKit.UILabel labelGoldBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelGoldBadges")));
			}
			set {
				this.SetNativeField("labelGoldBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelSilverBadges")]
		private MonoTouch.UIKit.UILabel labelSilverBadges {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelSilverBadges")));
			}
			set {
				this.SetNativeField("labelSilverBadges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelConnectionError")]
		private MonoTouch.UIKit.UILabel labelConnectionError {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelConnectionError")));
			}
			set {
				this.SetNativeField("labelConnectionError", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelLastUpdated")]
		private MonoTouch.UIKit.UILabel labelLastUpdated {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelLastUpdated")));
			}
			set {
				this.SetNativeField("labelLastUpdated", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textDebug")]
		private MonoTouch.UIKit.UITextView textDebug {
			get {
				return ((MonoTouch.UIKit.UITextView)(this.GetNativeField("textDebug")));
			}
			set {
				this.SetNativeField("textDebug", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonSafari")]
		private MonoTouch.UIKit.UIButton buttonSafari {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonSafari")));
			}
			set {
				this.SetNativeField("buttonSafari", value);
			}
		}
	}
}
